### ISSUE TITLE
dataZoom

### ISSUE THREAD

**Issue by kevin0713** [qiuweikangdev/taro-react-echarts#1]
是否支持dataZoom？初步测试dataZoom 无法进行拖拽和缩放。

**Comment by qiuweikangdev** [comment]
是支持的。
需要注意点：
1、在自定义构建，需要勾选dataZoom
自定义构建官网：https://echarts.apache.org/zh/builder.html
2、配置dataZoom: {type: 'slider'} 即可拖拽和缩放

**Comment by aslkami** [comment]
小程序上 dataZoom 垂直方向上滚动会影响body 滚动，h5不会，两指缩放 小程序只能一次

**Comment by qiuweikangdev** [comment]
> 小程序上 dataZoom 垂直方向上滚动会影响body 滚动，h5不会，两指缩放 小程序只能一次

属于小程序问题了，小程序本身对这个支持不友好

**Comment by wanglihuaya** [comment]
> > 小程序上 dataZoom 垂直方向上滚动会影响body 滚动，h5不会，两指缩放 小程序只能一次
> 
> 属于小程序问题了，小程序本身对这个支持不友好

大佬 有了解过 web分析 微信的官方小程序里面的 图表示怎么做的吗，缩放什么的 都很丝滑，他们不会是用的web-view吧
