### ISSUE TITLE
控制台报错

### ISSUE THREAD

**Issue by hugyu** [qiuweikangdev/taro-react-echarts#12]
![image](https://user-images.githubusercontent.com/92319342/198825614-55ff3430-b0fd-4603-bad9-c62ffd01e05b.png)

**Comment by qiuweikangdev** [comment]
不支持vue

**Comment by hugyu** [comment]
> 不支持vue

大佬 我用的react呀

**Comment by qiuweikangdev** [comment]
说明一下，你用的taro版本，h5还是小程序

**Comment by hugyu** [comment]
> 说明一下，你用的taro版本，h5还是小程序

3.5.4 小程序

**Comment by qiuweikangdev** [comment]
我刚试了一下，是正常呀
![image](https://user-images.githubusercontent.com/44153172/198833168-e95ace15-1ddf-4fa5-ba04-51e3e73fc344.png)

**Comment by hugyu** [comment]
> 我刚试了一下，是正常呀 ![image](https://user-images.githubusercontent.com/44153172/198833168-e95ace15-1ddf-4fa5-ba04-51e3e73fc344.png)

大佬，解决了，但是出现了一个新的问题怎么解决呀
![image](https://user-images.githubusercontent.com/92319342/198864730-0b042c1b-9625-48f4-be33-bc2e0051704a.png)
重叠在一起了

**Comment by eddylizhiming** [comment]
解决了，需要// 仅 webpack5 支持依赖预编译配置
    prebundle: {
      enable: false
    }

**Comment by hugyu** [comment]
> prebundle: {
>       enable: false
>    }

这是什么原理呢
