### ISSUE TITLE
首次渲染的时候，option传入的不是最新的值

### ISSUE THREAD

**Issue by hugyu** [qiuweikangdev/taro-react-echarts#14]
`  const handleEchartsData = dataList => {
      console.log('handleEchartsData');
      
    const xData: Array<string> = [];
      const yData: Array<number> = [];
      dataList.forEach(data => {
          xData.push(data['label'])
          yData.push(data['ticket_count']);
      });
        const newOption={
            legend: {
              top: 50,
              left: "center",
              z: 100
            },
            tooltip: {
              trigger: "axis",
              show: true,
              confine: true
            },
            xAxis: {
              type: "category",
                data: xData,
                axisLabel: {
                    interval: 0,
                    rotate: 30
              },
              axisTick: {
                alignWithLabel: true
                },
            },
            yAxis: {
                type: "value",
            },
            series: [
              {
                data: yData ,
                type: "bar"
              }
            ]
        }
        
      setOption(newOption)
      return [xData, yData];
      
  };`
`        <Echarts echarts={echarts} option={option} />
`
但是option首次渲染的时候还是根据defaultoption渲染的

**Comment by qiuweikangdev** [comment]
你代码写的有问题吧

**Comment by hugyu** [comment]
> 你代码写的有问题吧

哪里有问题呢

**Comment by qiuweikangdev** [comment]
看下具体代码，你是如何更新option的？
