### ISSUE TITLE
在退出页面的时候，销毁页面所有的Echarts实例

### ISSUE THREAD

**Issue by wanglihuaya** [qiuweikangdev/taro-react-echarts#17]
大佬，咱们目前销毁是在onChartReady中销毁，我想写在useDidHide 退出页面的时候，销毁页面所有的echarts实例，有什么好的方法嘛

**Comment by wanglihuaya** [comment]
我目前是用一个变量Flag来控制是否销毁，但是falg变换的时候onChartReady已经完成了，就不会触发了
再封装一层组件的意思是？大佬方便细说吗👀

**Comment by wanglihuaya** [comment]
我看组件的ref是undefined

**Comment by qiuweikangdev** [comment]
基于taro-react-echarts封装一层业务组件，在这个组件里，监听页面退出的时候，销毁实例

**Comment by wanglihuaya** [comment]
好嘞，我试试

**Comment by wanglihuaya** [comment]
大佬，最后是把你的源码拷下来，把echarts实例暴露出来，实现手动注销的，可算解决了，内存不漏了🤪

**Comment by wanglihuaya** [comment]
> 大佬，最后是把你的源码拷下来，把echarts实例暴露出来，实现手动注销的，可算解决了，内存不漏了🤪

目前项目中直接用的源码，我在你基础上改一点，重新发个自己的npm包，就自己用其他项目方便点，大佬介意嘛

**Comment by wanglihuaya** [comment]
> 如果你只是想暴露echarts实例，就加几行代码而已， 没必要自己发个包。。 你可以提pr，或者我晚点发个版本暴露出来吧

那我先提个pr，写的不好，大佬别介意，到时候你看要不要合进来
