### ISSUE TITLE
代码销毁组件的问题

### ISSUE THREAD

**Issue by wanglihuaya** [qiuweikangdev/taro-react-echarts#18]
老哥，我看代码里有写，卸载组件的时候销毁实例，但是一直没有触发，我怀疑是这个问题：

```
  // 销毁echarts实例
  const dispose = () => {
    if (canvasRef.current) {
      echarts?.dispose(canvasRef.current)
    }
  }
```
canvasRef.current 一直为null，我刚试了下，好像改成chartRef，就可以自己销毁了，不用我在外面再手动获取实例销毁了

老哥有时间看下这个问题

**Comment by qiuweikangdev** [comment]
那么细心，确实是，我等下修复一下

**Comment by wanglihuaya** [comment]
> 那么细心，确实是，我等下修复一下

找 修了两天echarts内存泄漏的问题了😭

**Comment by qiuweikangdev** [comment]
已经修复更新了
