### ISSUE TITLE
[问题]大家有没有碰到在微信小程序上显示的图表是低分辨率的，也就是1x的

### ISSUE THREAD

**Issue by helloint** [qiuweikangdev/taro-react-echarts#19]
比如如下图这个效果。
我设置的页面宽度是390（iPhone12）。我试过设置成2倍的780也不行。不知道是否要做些特殊配制？
![image](https://user-images.githubusercontent.com/4143533/209458566-4dd51bfb-7885-4bf8-802e-04a21fd4734f.png)

谢谢🙏

**Comment by qiuweikangdev** [comment]
真机预览也会模糊吗，我刚试了一下 没什么问题
![e6138af810eede352f7e5557257dd0d](https://user-images.githubusercontent.com/44153172/209522280-4828ce4e-2c96-4117-80e0-bb2d6816e7db.jpg)

**Comment by helloint** [comment]
> 真机预览也会模糊吗，我刚试了一下 没什么问题 ![e6138af810eede352f7e5557257dd0d](https://user-images.githubusercontent.com/44153172/209522280-4828ce4e-2c96-4117-80e0-bb2d6816e7db.jpg)

你有没有demo 微信小程序可以分享交流一下？
我最近又写了个小图表，也是同样的问题。
https://github.com/helloint/taro-shmetro
可能是我对微信小程序内的宽度理解还不够。我是设置的390宽，然后所有图表尺寸都是基于H5版本等比例（390/750）缩小。

**Comment by qiuweikangdev** [comment]
估计是你这里设置的问题，你研究下， devicePixelRatio我已经处理过了，你应该不需要管这个
![image](https://user-images.githubusercontent.com/44153172/209524818-69ce2e41-13f4-4c6d-95e5-89ac527a5e73.png)

**Comment by helloint** [comment]
> 估计是你这里设置的问题，你研究下， devicePixelRatio我已经处理过了，你应该不需要管这个 ![image](https://user-images.githubusercontent.com/44153172/209524818-69ce2e41-13f4-4c6d-95e5-89ac527a5e73.png)

去掉`devicePixelRatio`后就好了，谢谢👌
