### ISSUE TITLE
在h5中展示正常，在小程序中不展示

### ISSUE THREAD

**Issue by xgaxpp** [qiuweikangdev/taro-react-echarts#2]
`
import './index.scss'

import Echarts from 'taro-react-echarts';
import * as echarts from 'echarts';

const Index = () => {

  const options = {
    legend: {
      top: 50,
      left: 'center',
      z: 100
    },
    tooltip: {
      trigger: 'axis',
      show: true,
      confine: true
    },
    xAxis: {
      type: 'category',
      data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
      type: 'value'
    },
    series: [
      {
        data: [150, 230, 224, 218, 135, 147, 260],
        type: 'line'
      }
    ]
  }

  return (
     <Echarts  echarts={echarts} option={options} > </Echarts>
  );
};

export default Index;
`

**Comment by qiuweikangdev** [comment]
用的是最新版本v1.0.5 吗

**Comment by xgaxpp** [comment]
是的

**Comment by qiuweikangdev** [comment]
微信基础库版本是多少？ 需要大于2.9版本才能显示

**Comment by xgaxpp** [comment]
"@antmjs/vantui": "^1.9.14",
    "@babel/runtime": "^7.7.7",
    "@reduxjs/toolkit": "^1.8.3",
    "@tarojs/components": "3.5.0",
    "@tarojs/helper": "3.5.0",
    "@tarojs/plugin-framework-react": "3.5.0",
    "@tarojs/plugin-platform-alipay": "3.5.0",
    "@tarojs/plugin-platform-jd": "3.5.0",
    "@tarojs/plugin-platform-qq": "3.5.0",
    "@tarojs/plugin-platform-swan": "3.5.0",
    "@tarojs/plugin-platform-tt": "3.5.0",
    "@tarojs/plugin-platform-weapp": "3.5.0",
    "@tarojs/react": "3.5.0",
    "@tarojs/router": "3.5.0",
    "@tarojs/runtime": "3.5.0",
    "@tarojs/shared": "3.5.0",
    "@tarojs/taro": "3.5.0",
    "@tarojs/taro-h5": "3.5.0",
    "@types/echarts": "^4.9.16",
    "echarts": "^5.3.3",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-redux": "^8.0.2",
    "taro-hooks": "latest",
    "taro-react-echarts": "^1.0.5"


微信开发者工具最新版本

**Comment by qiuweikangdev** [comment]
![image](https://user-images.githubusercontent.com/44153172/182278858-1246d477-4726-43a4-b984-0ca19e85d177.png)
查看这里的基础库版本大于2.9
我这里试过了是正常的

**Comment by qiuweikangdev** [comment]
还有问题吗 @xgaxpp , 没问题我就关闭issue了
