### ISSUE TITLE
xAxis.data 没有传给echarts实例？

### ISSUE THREAD

**Issue by helloint** [qiuweikangdev/taro-react-echarts#20]
我在画这个[demo](https://echarts.apache.org/examples/en/editor.html?c=line-aqi)的时候，发现得到的图表数据异常，猜测是xAxis.data没有被传入`echart`（在原生版本中注释掉这行后得到的结果和异常结果一致）
原生版本：
<img width="593" alt="image" src="https://user-images.githubusercontent.com/4143533/211155425-d1f47cbb-97a1-42fe-b501-d863e2edb9be.png">
代码：https://github.com/helloint/covid/blob/master/js/metro.js#L160

Taro版本：
<img width="740" alt="image" src="https://user-images.githubusercontent.com/4143533/211155443-4b04c568-cf4a-47f3-a86b-e16a73124b37.png">
代码：https://github.com/helloint/taro-shmetro/blob/master/src/pages/chart/history.tsx#L111

Thanks.

**Comment by qiuweikangdev** [comment]
![image](https://user-images.githubusercontent.com/44153172/211156240-ee105ab1-ebab-4ccd-9e20-85a9bbbc1fb9.png)
为啥要这样写呢，这代码明显有问题

**Comment by helloint** [comment]
能否告知是哪方面的问题？
官方demo是这样写的，我就拿过来改了下。
看着好像也没问题，debug看过处理后的option的数据是正确的，但最终xAxis的数据没生效。

**Comment by helloint** [comment]
的确是我代码的问题，谢谢指正🙏
