### ISSUE TITLE
TypeError: el.removeEventListener is not a function

### ISSUE THREAD

**Issue by wozien** [qiuweikangdev/taro-react-echarts#23]
Taro 3.5 微信小程序端使用过程中抛出异常：
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/17634819/219256187-922bebc3-23da-4eb9-bc5f-b053db31ad1f.png">

调试断点，目测问题应该是 WxCanvas 类没有对应的方法：
<img width="772" alt="image" src="https://user-images.githubusercontent.com/17634819/219256394-a56d5207-27fa-4bdd-aead-7899eaaf9d7e.png">

**Comment by qiuweikangdev** [comment]
最近在忙，我晚点才能看看，你看看解决了的话提pr也可以

**Comment by wozien** [comment]
> 

已经提了哈

**Comment by qiuweikangdev** [comment]
更新了 v1.2.2

**Comment by wanglihuaya** [comment]
点赞，这个问题之前我还是 通过改echarts的源码解决的。。。
