### ISSUE TITLE
设置高度 height 为 100% 问题

### ISSUE THREAD

**Issue by wozien** [qiuweikangdev/taro-react-echarts#26]
当给图表手动设置一个100%父容器的高度时候，会出现高度不符合预测的情况：
<img width="577" alt="image" src="https://user-images.githubusercontent.com/17634819/221488800-fe0d0805-e5dc-4b58-a752-e99d04bde3b4.png">

运行结果：
<img width="429" alt="image" src="https://user-images.githubusercontent.com/17634819/221488745-23cd5714-af91-4ac0-b5e0-bad1516f3ddf.png">

源码调式结果：
在 initChart 函数里面是优先拿 style.height 高度，所以造成这个问题，可不可以直接拿 canvsRef.current.clientHeight?
<img width="974" alt="image" src="https://user-images.githubusercontent.com/17634819/221489064-a9b85558-4027-4007-bc3d-61d3b0534154.png">

**Comment by qiuweikangdev** [comment]
需要设置具体的style.height高度

**Comment by wozien** [comment]
> 需要设置具体的style.height高度

好吧，那只能在组件外包括一层了，拿到具体的高度传进去了
