### ISSUE TITLE
加载展示正常，当echart 是在二级页面 返回时。就会报错

### ISSUE THREAD

**Issue by sqleo** [qiuweikangdev/taro-react-echarts#4]
![image](https://user-images.githubusercontent.com/110551780/184780384-ccb46db5-5dda-46dd-aeaa-0d972258dbd3.png)

**Comment by sqleo** [comment]
Cannot read property 'getAttribute' of null

**Comment by qiuweikangdev** [comment]
能简单提供具体的代码吗，我好复现一下

**Comment by qiuweikangdev** [comment]
更新下1.0.8版本试试

**Comment by sqleo** [comment]
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/110551780/185016577-20a9f085-3d24-4c5e-815f-1f17ecbd5743.png">
<img width="545" alt="image" src="https://user-images.githubusercontent.com/110551780/185016661-1fbe721a-057f-4ee0-bae8-e24eb4142720.png">
还是会报错，二级页面返回的时候 就会报上名的错误

**Comment by qiuweikangdev** [comment]
你这个二级页面 具体是哪个页面，哪个页面跳哪里
你这里二级页面指的是 弹出框的页面吗

**Comment by qiuweikangdev** [comment]
你这个是 h5吗
