### ISSUE TITLE
使用echarts 主包体积过大 怎么优化呢？

### ISSUE THREAD

**Issue by FxlDeveloper** [qiuweikangdev/taro-react-echarts#47]

**Comment by qiuweikangdev** [comment]
1、自定义构建echarts包，减少echarts包体积
2、echarts放在分包加载

**Comment by FxlDeveloper** [comment]
感谢回复，主要是主包里有tabbar ，然后首屏就有echarts的使用。这种放在分包引用不到吧

**Comment by FxlDeveloper** [comment]
还有个问题，企业微信小程序里提示
![image](https://github.com/user-attachments/assets/fb629215-6ae4-437c-9978-8c0f25413484)
