### ISSUE TITLE
【小程序】 折线图的tooltip不显示是什么情况呢，请问有遇到过吗

### ISSUE THREAD

**Issue by SunshineH2** [qiuweikangdev/taro-react-echarts#6]

**Comment by SunshineH2** [comment]
![image](https://user-images.githubusercontent.com/31178307/188258809-d6b84865-dacb-44d4-a7dc-874699f9643a.png)

**Comment by SunshineH2** [comment]
十万火急！！求救🆘

**Comment by qiuweikangdev** [comment]
我这边是正常，你看下自定义构建的echarts，有没有勾选toolttip

**Comment by SunshineH2** [comment]
勾选了呢

**Comment by SunshineH2** [comment]
你的折线图的tooltip也是显示的吗，而且我这边，legend点击也无效，或者你方便告知你那里用的echarts的版本号是多少吗

**Comment by qiuweikangdev** [comment]
可能你构建的eharts有问题，你拿一下我demo例子的echarts试试
https://github.com/qiuweikangdev/taro-react-echarts/blob/ba55274cf847a6671d9b0534c93bc6acf0975e64/src/assets/js/echarts.js

**Comment by SunshineH2** [comment]
我用了你demo里的js试了，也是不显示tooltip哎

**Comment by SunshineH2** [comment]
而且我用的option就是你readme里面写的那个option，折线图的

**Comment by SunshineH2** [comment]
大佬能帮忙看看是啥问题吗，taro版本是3.4.12，构建成微信小程序

**Comment by SunshineH2** [comment]
import { useState } from 'react';

import { Flex } from '@taroify/core';
import { View } from '@tarojs/components';
import classNames from 'classnames';
import Echarts, { EChartOption } from 'taro-react-echarts';

import echarts from '../../../../assets/echarts-1';
import styles from './index.module.less';

export default function () {
  const categoryList = ['年', '月', '周', '日'];

  const [category, setCategory] = useState('年');

  const option: EChartOption = {
    legend: {
      top: 50,
      left: 'center',
      z: 100,
    },
    tooltip: {
      trigger: 'axis',
      show: true,
      confine: true,
    },
    xAxis: {
      type: 'category',
      data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    },
    yAxis: {
      type: 'value',
    },
    series: [
      {
        data: [150, 230, 224, 218, 135, 147, 260],
        type: 'line',
      },
    ],
  };

  return (
    <>
      <Echarts echarts={echarts} option={option}></Echarts>
      <Flex justify="space-around">
        {categoryList.map(item => (
          <View
            key={item}
            className={classNames([styles.item, item === category && styles.selected])}
            onClick={() => setCategory(item)}
          >
            {item}
          </View>
        ))}
      </Flex>
    </>
  );
}

**Comment by qiuweikangdev** [comment]
![image](https://user-images.githubusercontent.com/44153172/188356252-dc2de9cd-3656-4748-bd3d-f04cf55cfbf3.png)
可看下https://github.com/ecomfe/echarts-for-weixin 使用这个项目的ec-canvas/echarts.js

**Comment by SunshineH2** [comment]
这个我看了，这个人家支持tooltip是因为在代码里把touchMove等方法都绑定上去了，然后在外层通过disableTouch属性判断是否需要绑定touch事件，但是我看了下你的代码是没有绑定这些事件的，大佬能支持下吗？顺便问下为啥你那边可以显示tooltip呢

**Comment by qiuweikangdev** [comment]
微信小程序事件这个我看下，后续再加上， 我以为你说的h5，h5是可以显示

**Comment by SunshineH2** [comment]
太感谢了大佬！！我这边是小程序，一直都不显示

**Comment by qiuweikangdev** [comment]
升级1.1.3试试

**Comment by SunshineH2** [comment]
好的，我试下先

**Comment by SunshineH2** [comment]
可以了，大佬，十分感谢🙏
