### ISSUE TITLE
按照demo编写代码，以小程序的模式启动，控制台未报错，canvas没渲染出来

### ISSUE THREAD

**Issue by YoungHorn1999** [qiuweikangdev/taro-react-echarts#9]
<img width="478" alt="image" src="https://user-images.githubusercontent.com/39025558/190361235-add9196b-e401-40eb-b281-50716795425a.png">

看DOM层级发现没有渲染出组件
![image](https://user-images.githubusercontent.com/39025558/190360815-4fc4271b-5079-4eac-85f2-a864205eab4c.png)

**Comment by wanglihuaya** [comment]
这个我也有 昨天按的包在项目里，没问题，今天想着重新弄一个demo，重新Taro了一个新项目，然后也是这个问题，昨天的项目中没问题🥲

**Comment by YoungHorn1999** [comment]
老哥解决这个问题了吗

**Comment by wanglihuaya** [comment]
> 老哥解决这个问题了吗

之前项目中的能跑，新的demo 也是没有canvas标签

**Comment by qiuweikangdev** [comment]
> > 老哥解决这个问题了吗
> 
> 之前项目中的能跑，新的demo 也是没有canvas标签

你这个新的demo和之前的项目 是有什么区别吗

**Comment by YoungHorn1999** [comment]
在业务代码里面照着demo写的

![image](https://user-images.githubusercontent.com/39025558/190385531-6b1c6126-92f6-4fed-a4c1-2c63f01b933a.png)

canvas渲染出来了，图表没渲染出来，控制台报了这个错
![image](https://user-images.githubusercontent.com/39025558/190385160-e4dbfa61-8ef5-4d98-a4fc-6ed1bf5a17f6.png)

**Comment by YoungHorn1999** [comment]
有大佬能帮忙看一眼吗，我请你吃肯德基疯狂星期四

**Comment by qiuweikangdev** [comment]
你这个echarts是自己构建的吗

**Comment by qiuweikangdev** [comment]
> 有大佬能帮忙看一眼吗，我请你吃肯德基疯狂星期四

哈哈 点个star就好

**Comment by YoungHorn1999** [comment]
> 你这个echarts是自己构建的吗

这个echarts，自己构建的和从你demo里拉下来的都试了，都有这个问题

**Comment by qiuweikangdev** [comment]
设置isPage为false试下

**Comment by YoungHorn1999** [comment]
可能是因为echarts的引入方式，照这个方式引入，会报如下错误
<img width="462" alt="image" src="https://user-images.githubusercontent.com/39025558/190391999-43680b3a-b65f-4708-93aa-8b58e022498c.png">
<img width="910" alt="image" src="https://user-images.githubusercontent.com/39025558/190392067-ebfd4c2b-73e5-4b20-9b85-bc01e3fea44d.png">

然后我改成了import * as echarts from './echarts'，就会报j.setCanvasCreator is not a function

bytheway，试了isPage为false也没有成功

**Comment by qiuweikangdev** [comment]
主页上有我的邮箱，你压缩发给我，我有空看下

**Comment by YoungHorn1999** [comment]
我有个问题哈，这个echarts包如果不能这么引用的话，那个demo是咋跑起来的

**Comment by qiuweikangdev** [comment]
echarst包引入方式看的是这个echarts包如何导出的

**Comment by YoungHorn1999** [comment]
> echarst包引入方式看的是这个echarts包如何导出的

我用的是demo里的echarts包

**Comment by qiuweikangdev** [comment]
用的taro多少版本

**Comment by qiuweikangdev** [comment]
试下把prebundle关闭看看
 compiler: {
    type: "webpack5",
    prebundle: {
      enable: false
    }
  },

**Comment by qiuweikangdev** [comment]
可以先使用taro 3.5 以下的版本，或者先关闭预编译prebundle可以解决

**Comment by CloudyBao** [comment]
> 可以先使用taro 3.5 以下的版本，或者先关闭预编译prebundle可以解决

  compiler: {
    type: "webpack5",
    prebundle: {
      exclude: ["taro-react-echarts"],
    },
  },可以把这个写到readme里面么，不好找啊
